#define HAVE_DIRENT_H	0
#define HAVE_FCNTL_H	1
#define HAVE_LIMITS_H	1
#define HAVE_NDIR_H	0
#define HAVE_STDLIB_H	1
#define HAVE_STRING_H	1
#define HAVE_SYS_DIR_H	0
#define HAVE_SYS_FILE_H	1
#define HAVE_SYS_NDIR_H	0
#define HAVE_SYS_WAIT_H	0
#define HAVE_TIME_H	1
#define HAVE_UNISTD_H	0
#define HAVE_VFORK_H	0

#define HAVE_DUP2	1
#define HAVE_FORK	0
#define HAVE_MEMCHR	1
#define HAVE_STRCHR	1
#define HAVE_ST_BLKSIZE	0
